### ISSUE TITLE
Outdated list / maintenance

### ISSUE THREAD

**Issue by Ambrevar** [lu4nx/cl-tld#1]
The list is now outdated, would it be possible to update it?

Otherwise, would you recommend a fork?

**Comment by lu4nx** [comment]
Hi @Ambrevar, the list file has been updated.

You can also update manually:

```curl https://publicsuffix.org/list/public_suffix_list.dat -o effective_tld_names.dat```

**Comment by Ambrevar** [comment]
Perfect, thanks!
I was asking mostly for packaging purposes, it's much easier (and reproducible) if the embedded list is part of the repo.  Problem solved!
